import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

const ovo = Ovo({
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-ovo",
});

export const metadata = {
  title: "Gowthaman Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ovo.className}
        antialiased leading-8 overflow-x-hidden
        bg-white text-black
        dark:bg-[#140024] dark:text-white transition-colors duration-300`}
      >
    {children}
  </body>
</html>
  );
}